package privacyanalyzer.ui.view.analyze;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AnalyzeViewDesign extends VerticalLayout {
	protected Upload upload;
	protected ProgressBar progressBar;
	protected Label malwareStatus;
	protected Label nameLabel;
	protected TextField nameField;
	protected Label packageName;
	protected TextField packageNameField;
	protected Label packageVersionName;
	protected TextField packageVersionNameField;
	protected Label packageVersionCode;
	protected TextField packageVersionCodeField;
	protected Label minSDK;
	protected TextField minSDKField;
	protected Label targetSDK;
	protected TextField minSDKField1;
	protected Label sha256;
	protected TextField sha256Field;
	protected Grid declaredPermissionsGrid;
	protected Grid notDeclaredButUsedPermissionsGrid;
	protected Grid declaredAndUsedPermissionsGrid1;
	protected Grid declaredAndNotUsedPermissionsGrid11;
	protected Grid callsGrid;
	protected Grid trackersGrid;

	public AnalyzeViewDesign() {
		Design.read(this);
	}
}
